# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-spid-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.8
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - fastp=0.20.0
  - bbmap=38.69
  - samtools=1.9
  - pandas=0.25.3
  - raxml=8.2.12
  - pip:
    - biopython==1.73
